# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: true
dist: trusty
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
branches:
  only: master
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gcc gfortran -y ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:mc3man/trusty-media && sudo apt-get update && sudo apt-get install -y ffmpeg && ffmpeg -version ; fi
  - export PYTHON=""
